version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout  # This checks out the code from your repository
      - run:
          name: List Client Directory
          command: ls -la client  # Verify that package.json is in the client directory
      - run:
          name: Install dependencies
          command: |
            cd client
            npm install
      - run:
          name: Verify Node.js and npm versions
          command: |
            node -v
            npm -v
      - run:
          name: Run tests
          command: |
            cd client
            npm run test
      - run:
          name: Run lint
          command: |
            cd client
            npm run lint

workflows:
  my-workflow:
    jobs:
      - build
