version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    working_directory: ~/client  # Set the working directory to `client`
    steps:
      - checkout  # This checks out the code from your repository
      - run:
          name: Verify Directory Structure
          command: ls -la  # List files to verify that `client` and `package.json` exist
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Verify Node.js and npm versions
          command: |
            node -v
            npm -v
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run lint
          command: npm run lint

workflows:
  my-workflow:
    jobs:
      - build
